### PR TITLE
Uploader improvements

### PR DESCRIPTION
**Pull request by mrerrormessage**
- Adds a SHA1 to uploaded files, valuable for two reasons:
  - Allows us to tell what version of an assets is being served using just `curl -v` (supplied in the "x-amz-meta-sha1" header, can be compared to `shasum <generated file>`).
  - Saves thousands of uploads to amazon on every redeploy
- Adds a redirect for every `/x/` to `/x`

@TheBizzle and/or @qiemem , you're welcome to review and provide any feedback, if you would like. I'm planning to bump the version, merge and deploy this first thing tomorrow morning if there are no comments.

### CODE REVIEW

**Comment by qiemem** [comment]
> Saves thousands of uploads to amazon on every redeploy

Is this done by only uploading the changed files, so things like models that don't change often don't have to be re-uploaded everytime (I know, I know, I should just look through the code)? Is there consequently a quicker turnaround time between merges into master and updates on production?

**Comment by TheBizzle** [comment]
LGTM

**Comment by mrerrormessage** [comment]
@qiemem, you are completely correct about how it works - it does a request to see whether the file has changed before uploading, and only uploads if changed. I'm guessing there are on average 10-15 files that change per deploy for Galapagos. Models are a perfect example of a file that rarely changes.

I'm not sure how much of a speed-up we'll see. Right now, uploads take 30 seconds, which is pretty fast, given that we take 90 seconds to scrape (to ensure that lists of model compilation statuses compute before we scrape).
- Reducing the raw amount of data transferred should be a speed-up
- However, we're making more requests on average - one query for each file to see the current version, plus an additional upload if a file has changed.
- We also have to calculate the shasum of each file, which takes time: 26 seconds for all files that would be uploaded on my machine, probably slower on Travis.

I'm guessing that it will be much slower on the first go (since it will shasum and then re-upload), and slightly slower thereafter. There is definitely plenty of room here for parallelizing - only web requests are wrapped in futures at the moment.

**Comment by TheBizzle** [comment]
(The vast majority of the deployment lag, AFAIK, comes from the fact that Travis must first do a clean build/test of the code.)

**Comment by qiemem** [comment]
> (The vast majority of the deployment lag, AFAIK, comes from the fact that Travis must first do a clean build/test of the code.)

Ah, yes, of course. I should've realized. Still, this looks like a fantastic improvement.

**Pull request merged**
