### PR TITLE
Support Play 2.5

### PR DESCRIPTION
**Pull request by mrerrormessage**
This is blocking Galapagos from moving to Play 2.5.

Assigning @mrerrormessage.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
I'm in the process of testing this in Galapagos. While a lot of files were moved around, the number of files that were properly changed in a meaningful way is actually quite small:
- [build.sbt](https://github.com/NetLogo/Play-Scraper/pull/4/files#diff-fdc3abdfd754eeb24090dbd90aeec2ce): splitting into two projects
- [ApplicationScraper](https://github.com/NetLogo/Play-Scraper/pull/4/files#diff-bbca77bc523731b0222fc732d521a5ea): switching out play `Iteratee` for Akka Streams. (What even is a `Materializer`?)
- [PlayScrapePlugin](https://github.com/NetLogo/Play-Scraper/pull/4/files#diff-35b91c73712bc736ba04be027ddc23da): various sbt shenanigans to add the play-scrape-server jar of the same version as a dependency (and get it on the special Play classpath) without the user needing to add extra code. Also ensures that this plugin is only loaded when the Play sbt plugin is active, which should have been done all along.

**Comment by TheBizzle** [comment]
> What even is a `Materializer`?

I had the same question.  As far as I can tell, the answer is, "No one knows what it is, but everyone knows that you need one."

**Comment by mrerrormessage** [comment]
Perhaps the `Materializer` manages your backpressure?

**Comment by mrerrormessage** [comment]
Tested successfully on Galapagos, merging and updating on Bintray.

**Comment by SethTisue** [comment]
There is a split in Akka Streams, as in scalaz-stream and FS2 and other similar APIs, between the calls you use to define the structure of a computation in advance, and the calls for actually performing that computation. A materializer is the thing that actually runs a computation (e.g. by materializing actors to perform the tasks) once it has been defined.

If I understand FS2 correctly, the way they do the same thing is by asking you to specify an effect type, as a type parameter, and then requiring a typeclass instance to be in scope that knows how to run that effect type. So it ends up devolving to about the same thing, namely, that you have a value in implicit scope that knows how to make one of these graphs actually _do_ something.

**Comment by mrerrormessage** [comment]
@TheBizzle , you should need to only change the version of the plugin in Galapagos's `project/plugins.sbt` (well, and the version of the play sbt plugin) and it should work as before.

**Pull request merged**
